
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Dec 06 15:53:15 COT 2012
//----------------------------------------------------

package paquete;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VIA = 2;
  public static final int GUION = 5;
  public static final int BARRIO = 6;
  public static final int REF = 3;
  public static final int error = 1;
  public static final int NUMERAL = 4;
  public static final int EOF = 0;
}

